# Generated by Django 5.1.6 on 2025-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('logo', models.ImageField(upload_to=None, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='')),
            ],
        ),
    ]
